version: '3.8'

services:
  nestjs:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.production.docker
    ports:
      - 3000:3000
      # - 9229:9229
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres
    env_file:
      - .env.production.docker
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
