version: '3.8'

services:
  nestjs:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env.development.docker
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      # - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres
    env_file:
      - .env.development.docker
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
