version: '3.8'

services:
  nestjs:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.production.docker
    ports:
      - 3000:3000
      # - 9229:9229
    depends_on:
      - postgres
    restart: always
    networks:
      - web_network
  postgres:
    image: postgres
    env_file:
      - .env.production.docker
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - web_network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - web_network
    ports:
      - 5050:5050
    links:
      - nestjs

networks:
  web_network:
    driver: bridge

volumes:
  pgdata:
